name: CI Backend

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]

jobs:
  ci:
    uses: glop2026shoploc/.github/.github/workflows/ci-back.yml@main
    with:
      image-name: users
    permissions:
      contents: read
      packages: write